module.exports = {
  flags() {
    return {
      ERROR_USER_NOT_FOUND : 'ERROR_USER_NOT_FOUND',
      ERROR_USER_NAME_OR_PASSWORD_WRONG : 'ERROR_USER_NAME_OR_PASSWORD_WRONG',
      ERROR_USER_UUId_WRONG : 'ERROR_USER_UUId_WRONG',
      ERROR_USER_NAME_WRONG : 'ERROR_USER_NAME_WRONG',
      ERROR_USER_PASSWORD_WRONG : 'ERROR_USER_PASSWORD_WRONG',
      ERROR_UNKNOWN_USER_LOGIN_ERROR : 'ERROR_UNKNOWN_USER_LOGIN_ERROR',
      ERROR_UNKNOWN_USER_REGISTER_ERROR : 'ERROR_UNKNOWN_USER_REGISTER_ERROR',
      ERROR_ALREADY_LOGGED_IN : 'ERROR_ALREADY_LOGGED_IN',
      ERROR_NOT_LOGGED_IN : 'ERROR_NOT_LOGGED_IN',
      ERROR_UNKNOWN_SQL_CONNECTION_ERROR: 'ERROR_UNKNOWN_SQL_CONNECTION_ERROR',

      INFO_USER_LOGIN_SUCCEEDED : 'INFO_USER_LOGIN_SUCCEEDED',
      INFO_USER_REGISTER_SUCCEEDED : 'INFO_USER_REGISTER_SUCCEEDED',
    }
  }
};